name: Update Taipower Data

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Taipower Data
        run: |
          curl -L "https://service.taipower.com.tw/data/opendata/apply/file/d006001/001.json" -o taipower_generation.json
          curl -L "https://service.taipower.com.tw/data/opendata/apply/file/d006020/001.json" -o taipower_supply.json

      - name: Commit and Push update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add taipower_generation.json taipower_supply.json
          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "Auto update"
            git push origin main
          fi
