name: Update Taipower Data

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Download Taipower Data
        run: |
          curl -L "https://service.taipower.com.tw/data/opendata/apply/file/d006001/001.json" -o taipower_generation.json
          curl -L "https://service.taipower.com.tw/data/opendata/apply/file/d006020/001.json" -o taipower_supply.json

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add taipower_generation.json taipower_supply.json

          git commit -m "Auto update Taipower data $(date)" || echo "No changes"

          git push
