- name: Commit and Push update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add taipower_generation.json taipower_supply.json
          # 檢查是否有變動，避免空的 commit 導致報錯
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto update Taipower data ($(date +'%Y-%m-%d %H:%M'))"
            git push origin main
          fi
